name: cilia-env
channels:
- https://conda.binstar.org/menpo
- defaults
dependencies:
- asn1crypto=0.24.0=py35_0
- bleach=1.5.0=py35_0
- bokeh=0.12.13=py35h047fa9f_0
- bzip2=1.0.6=vc14_3
- certifi=2018.1.18=py35_0
- cffi=1.11.5=py35h945400d_0
- chardet=3.0.4=py35h177e1b7_1
- cloudpickle=0.5.2=py35_1
- colorama=0.3.7=py35_0
- cryptography=2.0.3=py35h67a4558_1
- cycler=0.10.0=py35_0
- dask=0.15.2=py35_0
- decorator=4.0.11=py35_0
- entrypoints=0.2.2=py35_1
- freetype=2.5.5=vc14_2
- h5py=2.7.0=np112py35_0
- hdf5=1.8.15.1=vc14_4
- html5lib=0.999=py35_0
- icu=57.1=vc14_0
- idna=2.6=py35h8dcb9ae_1
- imageio=2.2.0=py35hcd4b9a4_0
- ipykernel=4.5.2=py35_0
- ipython=5.2.2=py35_0
- ipython_genutils=0.1.0=py35_0
- ipywidgets=5.2.2=py35_1
- jinja2=2.9.4=py35_0
- jpeg=9b=vc14_0
- jsonschema=2.5.1=py35_0
- jupyter=1.0.0=py35_3
- jupyter_client=5.2.1=py35_0
- jupyter_console=5.2.0=py35hf76c22e_1
- jupyter_core=4.4.0=py35h629ba7f_0
- keras=2.1.2=py35_0
- libpng=1.6.27=vc14_0
- libprotobuf=3.2.0=vc14_0
- libtiff=4.0.6=vc14_3
- locket=0.2.0=py35h0dfcdd0_1
- markupsafe=0.23=py35_2
- matplotlib=2.0.0=np112py35_0
- mistune=0.7.3=py35_0
- mkl=2017.0.1=0
- nbconvert=5.1.1=py35_0
- nbformat=4.2.0=py35_0
- networkx=2.0=py35h29b0c50_0
- notebook=4.3.1=py35_1
- numpy=1.12.0=py35_0
- olefile=0.44=py35_0
- openssl=1.0.2k=vc14_0
- pandas=0.19.2=np112py35_1
- pandocfilters=1.4.1=py35_0
- partd=0.3.8=py35h894d1e4_0
- path.py=10.1=py35_0
- pickleshare=0.7.4=py35_0
- pillow=4.0.0=py35_1
- pip=9.0.1=py35_1
- prompt_toolkit=1.0.9=py35_0
- protobuf=3.2.0=py35_0
- pycparser=2.18=py35h15a15da_1
- pygments=2.1.3=py35_0
- pyopenssl=17.4.0=py35hc34edb9_0
- pyparsing=2.1.4=py35_0
- pyqt=5.6.0=py35_2
- pysocks=1.6.8=py35_0
- python=3.5.2=0
- python-dateutil=2.6.0=py35_0
- pytz=2016.10=py35_0
- pywavelets=0.5.2=py35h7c47ace_0
- pyyaml=3.12=py35h4bf9689_1
- pyzmq=16.0.2=py35_0
- qt=5.6.2=vc14_3
- qtconsole=4.2.1=py35_2
- requests=2.18.4=py35h54a615f_1
- scikit-image=0.13.1=py35hfa6e2cd_1
- scikit-learn=0.18.1=np112py35_1
- scipy=0.18.1=np112py35_1
- setuptools=27.2.0=py35_1
- simplegeneric=0.8.1=py35_1
- sip=4.18=py35_0
- six=1.10.0=py35_0
- tensorflow=1.1.0=np112py35_0
- testpath=0.3=py35_0
- tk=8.5.18=vc14_0
- toolz=0.9.0=py35_0
- tornado=4.4.2=py35_0
- traitlets=4.3.1=py35_0
- urllib3=1.22=py35h8cc84eb_0
- vc=14=h2379b0c_2
- vs2015_runtime=14.0.25420=0
- wcwidth=0.1.7=py35_0
- werkzeug=0.14.1=py35_0
- wheel=0.29.0=py35_0
- widgetsnbextension=1.2.6=py35_0
- win_inet_pton=1.0.1=py35hbef1270_1
- win_unicode_console=0.5=py35_0
- yaml=0.1.7=hc54c509_2
- zlib=1.2.8=vc14_3
- opencv3=3.1.0=py35_0
prefix: conda\envs\tf3

